name: fb_connector
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  ffigen: ^4.1.3
  lints: ^1.0.0
  test: ^1.16.0
ffigen:
  output: 'lib/src/fb_bindings.dart'
  headers:
    entry-points:
      - 'headers/ibase.h'
  name: 'FirebirdBindings'
  description: 'Bindings to Firebird'

dependencies:
  ffi:
  fixnum: